<?php

namespace Database\Seeders;

use App\Models\Shop;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ShopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $shops = [
            [
                'image' => 'antapani.png',
                'name' => 'Sorcha Antapani',
                'location' => 'Jl Subang Raya No.34 RT.04/RW.02 , Kec.Antapani, Kel.Antapani Tengah, Kota Bandung, Jawa Barat 40291',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 0,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 17000,
                'rate' => 4.1,
            ],
            [
                'image' => 'batununggal.png',
                'name' => 'Sorcha Batununggal',
                'location' => 'Jl. Suka Ati Raya No.14, Pasirluyu, Kec. Regol, Kota Bandung, Jawa Barat 40254',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 23000,
                'rate' => 4.3,
            ],
            [
                'image' => 'arcamanik.png',
                'name' => 'Sorcha Arcamanik',
                'location' => 'Ruko Radenia, Jl. Cisaranten Kulon, Kec. Arcamanik, Kota Bandung, Jawa Barat 40293',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 0,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 15000,
                'rate' => 4.2,
            ],
            [
                'image' => 'kosambi.png',
                'name' => 'Sorcah Kosambi',
                'location' => 'jl. Samoja No.8, Samoja, Kec. Batununggal, Kota Bandung, Jawa Barat 40273',
                'city' => 'Bandung',
                'delivery' => 1,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 31000,
                'rate' => 4.9,
            ],
            [
                'image' => 'gasibu.png',
                'name' => 'Sorcha Laundry Gasibu',
                'location' => 'Jl. Haur Pancuh No.01, Lebakgede, Kecamatan Coblong, Kota Bandung, Jawa Barat 40132',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 0,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 16000,
                'rate' => 4.0,
            ],
            [
                'image' => 'tubagus.png',
                'name' => 'Sorcha Laundry Tubagus',
                'location' => 'Jl. Tubagus Ismail Dalam No.54, Lebakgede, Kecamatan Coblong, Kota Bandung, Jawa Barat 40132',
                'city' => 'Bandung',
                'delivery' => 1,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 20000,
                'rate' => 4.5,
            ],
            [
                'image' => 'kircon.png',
                'name' => 'Sorcha Laundry Kircon',
                'location' => 'Jl. Babakan Sari 1 no 152, Babakan Sari, Kec. Kiaracondong, Kota Bandung, Jawa Barat 40283',
                'city' => 'Bandung',
                'delivery' => 1,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 19500,
                'rate' => 4.1,
            ],
            [
                'image' => 'pajajaran.png',
                'name' => 'Sorcha Laundry Padjajaran',
                'location' => 'Jl. Rama No.26, Kel. Arjuna, Kec. Cicendo, Kota Bandung, Jawa Barat 40172',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 0,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 20000,
                'rate' => 4.2,
            ],
            [
                'image' => 'cihampelas.png',
                'name' => 'Sorcha Laundry Cihampelas ',
                'location' => 'Jl. Boscha No. 33 (Cipaganti), Kecamatan Sukajadi, Kota Bandung, Jawa Barat',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 0,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 20000,
                'rate' => 4.2,
            ],
            [
                'image' => 'bubat.png',
                'name' => 'Sorcha Laundry Buah Batu ',
                'location' => 'Jl. Batu Kencana No.24, Turangga, Kec. Lengkong, Kota Bandung, Jawa Barat ',
                'city' => 'Bandung',
                'delivery' => 1,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 22000,
                'rate' => 4.4,
            ],
            [
                'image' => 'cibadak.png',
                'name' => 'Sorcha Laundry Cibadak',
                'location' => 'Jalan Luna IV No. 25/23 B, Kel. Jamika, Kec. Bojongloa Kidul, Kota Bandung, Jawa Barat 40241',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 23000,
                'rate' => 4.3,
            ],
            [
                'image' => 'cikutra.png',
                'name' => 'Sorcha Laundry Cikutra ',
                'location' => 'Jalan Terusan Batik Halus No. 12A, Sukaluyu, Cibeunying Kaler, Kota Bandung, Jawa Barat 40123',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 0,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 15000,
                'rate' => 4.2,
            ],
            [
                'image' => 'dago.png',
                'name' => 'Sorcha Laundry Dago',
                'location' => 'Jl. Raya Golf Dago No.1 , Ciburial, Kec. Cimanyan, Kab. Bandung, Jawa Barat 40135',
                'city' => 'Bandung',
                'delivery' => 1,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 31000,
                'rate' => 4.9,
            ],
            [
                'image' => 'cisitu.png',
                'name' => 'Sorcha Laundry Cisitu',
                'location' => 'Jl. Cisitu Lama No.33A, Dago, Kecamatan Coblong, Kota Bandung, Jawa Barat 40135',
                'city' => 'Bandung',
                'delivery' => 0,
                'pickup' => 0,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 16000,
                'rate' => 4.0,
            ],
            [
                'image' => 'pasteur.png',
                'name' => 'Sorcha Laundry Pasteur',
                'location' => 'Jl. Sukaraja No.2c No.295, Sukaraja, Kec. Cicendo, Kota Bandung, Jawa Barat 40175',
                'city' => 'Bandung',
                'delivery' => 1,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 20000,
                'rate' => 4.5,
            ],
            [
                'image' => 'antapani.png',
                'name' => 'Sorcha Laundry Antapani',
                'location' => 'Jl. Subang No.32, RT.04/RW.02, Antapani Tengah, Kec. Antapani, Kota Bandung, Jawa Barat 40291',
                'city' => 'Bandung',
                'delivery' => 1,
                'pickup' => 1,
                'whatsapp' => '62081111112731',
                'description' => 'layanan jasa laundry kiloan, satuan, sepatu, tas, baby stroller, karpet, dan lainnya. kami juga melayani pickup delivery atau antar jemput t',
                'price' => 19500,
                'rate' => 4.1,
            ],
        ];

        foreach ($shops as $shopItem) {
            Shop::create($shopItem);
        }
    }
}
